// <auto-generated />
using System;
using BlazorBooks.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorBooks.Api.Migrations
{
    [DbContext(typeof(BlazorBooksDbContext))]
    [Migration("20240201153025_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorBooks.Api.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountPages")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Robert Kiyosaki",
                            CountPages = 336,
                            DatePublished = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rich Dad Poor Dad is Robert's story of growing up with two dads his real father and the father of his best friend, his rich dad and the ways in which both men shaped his thoughts about money and investing. The book explodes the myth that you need to earn a high income to be rich and explains the difference between working for money and having your money work for you.",
                            GenreId = 1,
                            ImageURL = "/Images/Finance/Finance1.png",
                            Language = 0,
                            Price = 100m,
                            Title = "Rich Dad Poor Dad: What the Rich Teach Their Kids About Money That the Poor and Middle Class Do Not!"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "James Clear",
                            CountPages = 320,
                            DatePublished = new DateTime(2018, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
                            GenreId = 1,
                            ImageURL = "/Images/Finance/Finance2.png",
                            Language = 0,
                            Price = 100m,
                            Title = "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Héctor García, Francesc Miralles",
                            CountPages = 208,
                            DatePublished = new DateTime(2016, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "According to the Japanese, everyone has an ikigai—a reason for living. And according to the residents of the Japanese village with the world’s longest-living people, finding it is the key to a happier and longer life. Having a strong sense of ikigai—where what you love, what you’re good at, what you can get paid for, and what the world needs all overlap—means that each day is infused with meaning. It’s the reason we get up in the morning. It’s also the reason many Japanese never really retire (in fact there’s no word in Japanese that means retire in the sense it does in English): They remain active and work at what they enjoy, because they’ve found a real purpose in life—the happiness of always being busy.",
                            GenreId = 1,
                            ImageURL = "/Images/Finance/Finance3.png",
                            Language = 0,
                            Price = 100m,
                            Title = "Ikigai: The Japanese Secret to a Long and Happy Life"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "George S. Clason",
                            CountPages = 100,
                            DatePublished = new DateTime(1926, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The ancient Babylonians were the first people to discover the universal laws of prosperity. In his classic bestseller, \"The Richest Man in Babylon,\" George S. Clason reveals their secrets for creating, growing, and preserving wealth.",
                            GenreId = 1,
                            ImageURL = "/Images/Finance/Finance4.png",
                            Language = 0,
                            Price = 100m,
                            Title = "The Richest Man in Babylon"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Diana Wynne Jones",
                            CountPages = 448,
                            DatePublished = new DateTime(1986, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This entrancing classic fantasy novel is filled with surprises at every turn. An international bestseller, this much-loved book is the source for the Academy Award nominee for Best Animated Feature.\r\n\r\nSophie has the great misfortune of being the eldest of three daughters, destined to fail miserably should she ever leave home to seek her fate. But when she unwittingly attracts the ire of the Witch of the Waste, Sophie finds herself under a horrid spell that transforms her into an old lady. Her only chance at breaking it lies in the ever-moving castle in the hills: the Wizard Howl's castle.",
                            GenreId = 2,
                            ImageURL = "/Images/Fantasy/FairyTale1.png",
                            Language = 0,
                            Price = 11.99m,
                            Title = "Howl's Moving Castle"
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Diana Wynne Jones",
                            CountPages = 400,
                            DatePublished = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In this stunning sequel to Howl's Moving Castle, Diana Wynne Jones has again created a large-scale, fast-paced fantasy in which people and things are never quite what they seem.\r\n\r\nAbdullah was a young and not very prosperous carpet dealer. His father, who had been disappointed in him, had left him only enough money to open a modest booth in the Bazaar. When he was not selling carpets, Abdullah spent his time daydreaming. In his dreams he was not the son of his father, but the long-lost son of a prince. There was also a princess who had been betrothed to him at birth. He was content with his life and his daydreams until, one day, a stranger sold him a magic carpet.",
                            GenreId = 2,
                            ImageURL = "/Images/Fantasy/FairyTale2.png",
                            Language = 0,
                            Price = 11.99m,
                            Title = "Castle in the Air"
                        },
                        new
                        {
                            Id = 7,
                            AuthorName = "Наталья Щерба",
                            CountPages = 368,
                            DatePublished = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Василиса – обычная земная девочка, живущая с бабушкой, – неожиданно узнает, что ее отец – влиятельный маг Эфлары, мира, построенного на особой часовой магии. Попав в страну часодеев, фей и лютов, Василиса оказывается в центре опасной игры. Даже друзья не могут понять, кто же она сама? Неумеха, ничего не знающая о своем происхождении? Шпионка, засланная отцом, чтобы заполучить трон? Или могущественная часовщица, которая умеет управлять временем и может спасти Землю и Эфлару от грядущего столкновения?",
                            GenreId = 2,
                            ImageURL = "/Images/Fantasy/FairyTale3.png",
                            Language = 1,
                            Price = 11.99m,
                            Title = "Часодеи. Часовой ключ"
                        },
                        new
                        {
                            Id = 8,
                            AuthorName = "Naomi Simmons",
                            CountPages = 130,
                            DatePublished = new DateTime(2008, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Family and Friends offers a carefully graded approach to reading, writing and literacy skills in English to young learners. No other course offers you the same benefits as Family and Friends. The exceptionally strong skills training programme includes a focus on real speaking and writing output. Plus - the amazing package of integrated print and digital resources suits all teaching situations and learner types, supporting students, teachers, and parents. Use it with Little Friends and First Friends to make it an eight or nine-year course.",
                            GenreId = 3,
                            ImageURL = "/Images/Grammar/Educational1.png",
                            Language = 0,
                            Price = 63.73m,
                            Title = "FAMILY & FRIENDS 2E: 1 CLASS BOOK WITH STUDENT MULTIROM"
                        },
                        new
                        {
                            Id = 9,
                            AuthorName = "Tim Falla, Paul A Davies, Jane Hudson",
                            CountPages = 152,
                            DatePublished = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Solutions offers a carefully graded approach to reading, writing and literacy skills in English to young learners. No other course offers you the same benefits as Solutions. The exceptionally strong skills training programme includes a focus on real speaking and writing output. Plus - the amazing package of integrated print and digital resources suits all teaching situations and learner types, supporting students, teachers, and parents.",
                            GenreId = 3,
                            ImageURL = "/Images/Grammar/Educational2.png",
                            Language = 0,
                            Price = 63.73m,
                            Title = "Solutions Third Edition: Advanced STUDENT'S BOOK"
                        },
                        new
                        {
                            Id = 10,
                            AuthorName = "DK",
                            CountPages = 128,
                            DatePublished = new DateTime(2020, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Math makes the world go around. An educational book that will give you surprising answers to everyday math challenges. \r\n\r\nThis book unpacks how math is an essential part of our everyday life in ways that you never thought of. Full of crazy facts, magic tricks, and mathematical brainteasers and beautiful illustrations show you that math is interesting, fun, and not intimidating at all!",
                            GenreId = 4,
                            ImageURL = "/Images/Encyclopedia/Encyclopedia1.png",
                            Language = 0,
                            Price = 16.30m,
                            Title = "What's the Point of Math? (DK What's the Point of?)"
                        });
                });

            modelBuilder.Entity("BlazorBooks.Api.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("BlazorBooks.Api.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BlazorBooks.Api.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreName = "Finance"
                        },
                        new
                        {
                            Id = 2,
                            GenreName = "Fantasy"
                        },
                        new
                        {
                            Id = 3,
                            GenreName = "Grammar"
                        },
                        new
                        {
                            Id = 4,
                            GenreName = "Encyclopedia"
                        });
                });

            modelBuilder.Entity("BlazorBooks.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazorBooks.Api.Entities.Book", b =>
                {
                    b.HasOne("BlazorBooks.Api.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
